on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

os: [linux]
dist: focal
language: node_js
node_js: lts/*
before_install:
  - npm i -g npm@8.4.0

script:
  - echo 'Starting Build'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running Tests'
  - mocha

notifications:
  email:
    recipients:
      - dmreh@outlook.com
    on_failure: always
    on_success: change
